package com.ramas.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    SUBMISSION_CREATED,
    SUBMISSION_UPDATED,
    SUBMISSION_SUBMITTED,
    REVIEWER_CREATED,
    REVIEWER_UPDATED,
    CONFLICT_DECLARED,
    ASSIGNMENT_RUN_STARTED,
    ASSIGNMENT_RUN_COMPLETED,
    ASSIGNMENT_COMMITTED,
    ASSIGNMENT_OVERRIDDEN,
    REVIEW_SUBMITTED,
    USER_ROLE_CHANGED,
    EXPERIMENT_RUN
}
